### ISSUE TITLE
How to measure selected object in Product Workbench

### ISSUE THREAD

**Issue by tcrakshi** [evereux/pycatia#102]
Hi,
 i am working in product  workbench, user will select the edge/face/surface, 
i want call measurable object on the selected object and retrrive measurable component.

for Example:
User selected Circle in Product Workbench  - in program i would like to retrieve circle center co-ordinate , circle axis coordinate , etcc

is there any example?

**Comment by evereux** [comment]
Please note: items will need to be in design more for this example to work.

For this example i have selected the radius / edge of a PartBody within a Product.


```pytyhon

from pycatia import catia
from pycatia.product_structure_interfaces.product import Product

# note, items will need to be in design more for this example to work.
# for this example i have selected the radius / edge of a PartBody.

caa = catia()

document = caa.active_document
spa_workbench = document.spa_workbench()
product = Product(document.product.com_object)


selection = document.selection
selected_element = selection.item(1)
value = selected_element.value
reference = selected_element.reference

measurable = spa_workbench.get_measurable(reference)
print(measurable.radius)
```
