### ISSUE TITLE
About hide/show option using pycatia

### ISSUE THREAD

**Issue by VBG8** [evereux/pycatia#112]
Hello Evereux! How are you? 
I would like to know how can I hide/show a CATPart that belongs to a Product.
I want to hide some CATParts within a Product in order to generate a ALLCATPart of the whole product so the ALLCATPart doesn't save the CATParts hidden.
Thank you!

**Comment by evereux** [comment]
This will unhide all the items immediately under the root product.

```python
from pycatia import catia
from pycatia.product_structure_interfaces.product import Product

caa = catia()

document = caa.active_document
product = Product(document.product.com_object)

sub_products = product.products

for sub_product in sub_products:
    selection = document.selection

    selection.clear()
    selection.add(sub_product)

    selection.vis_properties.set_show(0)

```
