### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by tcrakshi** [evereux/pycatia#118]
i have knowledge on how to create automation interface by using CAA,  how can i contribute to this forum,

**Comment by evereux** [comment]
* Read the existing documentation there's some clues there.
* Put more effort into posting here. Look at this issue title for starters, it tells me nothing.
* Help expand on the tests.
* Help other users who ask questions.
* Create *simple* examples that use features of pycatia not already covered in the examples.
* Look at the codebase and see if there are any todo's that you can fix.

**Comment by evereux** [comment]
Added a CONTRIBUTING.md that briefly covers more what can be done to help.
