### ISSUE TITLE
[BUG]How to manage error ?

### ISSUE THREAD

**Issue by Djey51** [evereux/pycatia#129]
Hello,
Globally, what is the way to manage an error?
I mean in vba for catia you have for exemple the famous "on error resume next" to avoid to stop your code if an object doesn't exist in catia for example.

Is there a specific pycatia way or it is a more general python way of working?

Thanks

**Comment by Mithro86** [comment]
Use "Try Except".

More info:
https://www.w3schools.com/python/python_try_except.asp

**Comment by Djey51** [comment]
Thanks @Mithro86 ,

It is the way that I have already taken.
