### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by ptm-tm** [evereux/pycatia#137]
need add property
part.hybrid_shape_factory
part.hybrid_bodies
document.part

autocomplete is not worked(
![Снимок экрана 2023-03-02 164432](https://user-images.githubusercontent.com/9925925/222445676-e9ce8e83-0512-422b-84ae-5e188ef46929.png)

**Comment by deloarts** [comment]
See [#107](https://github.com/evereux/pycatia/issues/107#issuecomment-1336195688)

**Comment by ptm-tm** [comment]
yes its the same)
