### ISSUE TITLE
[BUG] missing function CreateReferenceFromGeometry

### ISSUE THREAD

**Issue by ptm-tm** [evereux/pycatia#142]
**Describe the bug**
mech mod interface .part has not this function
![image](https://user-images.githubusercontent.com/9925925/224023169-8b476013-4e0b-4dc4-9767-adf730314837.png)

**Comment by evereux** [comment]
The only reference I have to this in my documentation is for the `AnalysisManager` workbench.

How does this work? How does this differ from `CreateReferenceFromObject`?

**Comment by evereux** [comment]
I've now added this class method to the developement branch.
