### ISSUE TITLE
[BUG] wing_surface_from_naca_profile changing surface colour

### ISSUE THREAD

**Issue by evereux** [evereux/pycatia#168]
**Describe the bug**
The script `user_scripts/wing_surface_from_naca_profile.py` isn't changing the colour of the surface `MasterGeometry/Surface.WingSurface`.

**To Reproduce**
Run the script `python .\user_scripts\wing_surface_from_naca_profile.py`.

See lines from 273 - 279.

You'll need the latest developement branch to run this (until 0.6.2 is released) as there are bug fixes to pycatia that are required to run it. 

**Expected behavior**
The colour of the surface should change.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CATIA V5 r21
 - pycatia version: 0.6.2 (developement only currently)

I've been trying to fix this for awhile and can't figure out why it doesn't work. It's likely something simple I'm missing.

Running this standalone script behaves as expected.

```python

from pycatia import catia

from pycatia.mec_mod_interfaces.part import Part
from pycatia.product_structure_interfaces.product import Product

caa = catia()
application = caa.application
document = application.active_document
part = Part(application.active_document.part.com_object)
product = Product(application.active_document.product.com_object)
hybrid_bodies = part.hybrid_bodies

hb_mg = hybrid_bodies.get_item_by_name("MasterGeometry")
hb_mg_hs = hb_mg.hybrid_shapes
surface_wing = hb_mg_hs.get_item_by_name("Surface.WingSurface")
selection = document.selection
selection.add(surface_wing)
vis_properties = selection.vis_properties
vis_properties.set_real_color(0, 255, 0, 0)
```

@deloarts or @ptm-tm could you take a look?

**Comment by deloarts** [comment]
There are 2 solutions to this problem:

- Update the part first, otherwise the Surface.WingSurface element isn't available (see PR #169)
- Set the color to the geometrical set MasterGeometry

# Solution 1:
![image](https://github.com/evereux/pycatia/assets/12500350/8427629b-5038-4381-86ae-d53bd07727d9)

# Solution 2:
```python
set_colour(selection, gs_master_geometry, colour)
```
instead of
```python
set_colour(selection, surface_wing, colour)
```

**Comment by evereux** [comment]
You know I did think about updating the part but thought "well, I didn't have to do that to do this anywhere else so why would that work here" and dismissed it.

Thankyou!

**Comment by deloarts** [comment]
Yeah, not updating stuff did cost me a lot of time in the past, so it's my go-to solution now 😄

**Comment by ptm-tm** [comment]
update surfase

**Comment by ptm-tm** [comment]
and i prefer
```
    Wireframe_Bounding_Box = hsf.add_new_join('some items)
    # add vis property to wireframe bounding box
    selection.add(Wireframe_Bounding_Box)
    selection.vis_properties.set_real_width(2, 0)
    selection.vis_properties.set_real_color(255, 255, 8, 0)
    selection.vis_properties.set_real_opacity(180, 0)
    selection.clear()
```

**Comment by evereux** [comment]
I got rid of the get_item_by_name to get the surface and just used the existing hs_loft. It's how I originally had it but was trying other things.

I don't understand why we would use `hsf.add_new_join()`? This would create a new surface which seems redundant?

**Comment by ptm-tm** [comment]
> I got rid of the get_item_by_name to get the surface and just used the existing hs_loft. It's how I originally had it but was trying other things.
> 
> I don't understand why we would use `hsf.add_new_join()`? This would create a new surface which seems redundant?

its not nessesary to use hsf.add_new_join() its can be any Reference().
and i use part.update_object(ref) before apply vis settings to ref. in standart documentation and sample example use global part.update

**Comment by evereux** [comment]
> its not nessesary to use hsf.add_new_join() its can be any Reference().

I don't understand why you suggested it in the context of this discussion. You didn't answer that which is what my question was.

> its can be any Reference()

It doesn't need to be a `Reference()`. This script uses a `HybridShape()`.
