### ISSUE TITLE
[BUG] Parameters.is_list_parameter PR #172

### ISSUE THREAD

**Issue by evereux** [evereux/pycatia#173]
**Describe the bug**
Running the tests on the developement branch since the addition of pr #172 results in two failures.

```
FAILED tests\in\knowledgeware\test_knowledgeware_parameters.py::test_parameters_name - AttributeError: 'Parameters' object has no attribute 'is_list_parameter'
```

**To Reproduce**

```
pytest tests\in\knowledgeware\test_knowledgeware_parameters.py::test_parameters_name
```

```
pytest tests\in\knowledgeware\test_knowledgeware_parameters.py::test_sub_list
```

**Expected behavior**
Tests to complete successfully.

@Mithro86 can you take a look at fixing this bug please? There is no `Parameters.is_list_parameter`?

**Comment by Mithro86** [comment]
Sure! I will have a look

**Comment by evereux** [comment]
Thanks!
