### ISSUE TITLE
how to load？

### ISSUE THREAD

**Issue by simonasdmd** [evereux/pycatia#18]
Hello

There are 3drep files in my 3DXML file.

How should this file be loaded.

![image](https://user-images.githubusercontent.com/42527845/78659818-9b415d80-78fe-11ea-8cf1-1f368f60b3ae.png)

**Comment by evereux** [comment]
What problem with pycatia are you having exactly? What have you tried?

If you were opening these files in CATIA what would you do?

Can you provide examples files so that I may try and reproduce the problem?

**Comment by simonasdmd** [comment]
hi~ drop-dead gorgeous'
I use CATIA to open the 3DXML file. Then save the file as well. Save to 3DS format.
I want to do this with pycatia.
Can pycatia be implemented?
With my test data.
[test.zip](https://github.com/evereux/pycatia/files/4447808/test.zip)

**Comment by evereux** [comment]
That should work. Have you taken a look at the examples? There is one that shows you how to open a file and save it as another file type.

**Comment by simonasdmd** [comment]
I tried it locally. Maybe it's because I'm not familiar. Still unsuccessful. Do you have examples of tests there? Can you give it a try.

**Comment by evereux** [comment]
Example 8 shows how to open all .CATParts in a folder and save them as IGS. It should be quite straight forward to adapt that. However, when trying to do this manually with CATIA V5 I don't see an option to save as 3DS. Is that even possible? This is why I asked:

> If you were opening these files in CATIA V5 what would you do?

If you can't do it from within CATIA V5 itself, you can't do it with pycatia.

**Comment by simonasdmd** [comment]
My software is this

![image](https://user-images.githubusercontent.com/42527845/78879479-8394e100-7a86-11ea-9549-4bcc9bb1fa5b.png)

![image](https://user-images.githubusercontent.com/42527845/78879321-51837f00-7a86-11ea-95f2-0c4cf59fd269.png)

**Comment by simonasdmd** [comment]
Is this CATIA V5?

**Comment by evereux** [comment]
No.

**Comment by evereux** [comment]
Closing issue as one of the prerequisites of pycatia is not satisfied (having CATIA V5 actually installed). See https://github.com/evereux/pycatia/issues/19#issuecomment-611451098 for further information.
