### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by simonasdmd** [evereux/pycatia#19]
hi
I followed the installation instructions and an error occurred at the last step.
What is the cause.
![image](https://user-images.githubusercontent.com/42527845/78755128-3d1e8400-79ab-11ea-8b25-3c87526c1d79.png)

**Comment by evereux** [comment]
I'm assuming here you installed from pypi? It seems the 0.1.8 build is incomplete. Also, the docs need updating for that version. I'll get this fixed today.

Thanks for reporting.

**Comment by evereux** [comment]
I've now updated pycatia.

Can you please try:
    pip install pycatia==0.2.0

Also, note the import command is now (docs are updataed, you may need to F5 and refresh the page/s).
    (env) C:\Users\<username>\python\pycatia-scripts>python
    Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pycatia.base_interfaces import CATIADocHandler    
    >>> help(CATIADocHandler)

**Comment by simonasdmd** [comment]
I did solve yesterday's problem as you said. But as I continue to try "example" 2. Py. A new error has been encountered. It's my way of doing things, isn't it？

![image](https://user-images.githubusercontent.com/42527845/78874473-05810c00-7a7f-11ea-9256-6fac6777c287.png)

**Comment by simonasdmd** [comment]
(env) C:\Users\zhangweiqiang\python\pycatia-scripts\env\Scripts>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycatia.base_interfaces import CATIADocHandler
>>> from pycatia.space_analyses_interfaces import CATIAMeasurable
>>> from pycatia.space_analyses_interfaces import create_measurable
>>> from pycatia.workbenches import create_spa_workbench
>>> catia = CATIAApplication()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'CATIAApplication' is not defined
>>> from pycatia.base_interfaces import CATIAApplication
>>> catia = CATIAApplication()
Traceback (most recent call last):
  File "C:\Users\zhangweiqiang\python\pycatia-scripts\env\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, '无效的类字符串', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zhangweiqiang\python\pycatia-scripts\env\lib\site-packages\pycatia\base_interfaces\catia_application.py", line 48, in __init__
    self.catia = Dispatch('CATIA.Application')
  File "C:\Users\zhangweiqiang\python\pycatia-scripts\env\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\zhangweiqiang\python\pycatia-scripts\env\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\zhangweiqiang\python\pycatia-scripts\env\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, '无效的类字符串', None, None)
>>>

**Comment by evereux** [comment]
>  It's my way of doing things, isn't it？

Yes. :smile: 

Your code:

    from pycatia.base_interfaces import CATIADocHandler
Example 2 code:

    from pycatia.base_interfaces import CATIAApplication

**Comment by evereux** [comment]
My bad! I didn't read through properly sorry.

Do you have CATIA V5 running? If so and this still happens my hunch is that the COM objects haven't been registered properly. Re-installation should solve this.

**Comment by simonasdmd** [comment]
My software is this
![image](https://user-images.githubusercontent.com/42527845/78879065-f5205f80-7a85-11ea-9e72-75f529f2df60.png)


![image](https://user-images.githubusercontent.com/42527845/78879189-213be080-7a86-11ea-83c6-1320853260e4.png)

**Comment by simonasdmd** [comment]
Is this CATIA V5?

**Comment by evereux** [comment]
> Is this CATIA V5?

No sir. That is CATIA Composer. First I've ever heard of it.

**Comment by simonasdmd** [comment]
Can't I use pycatia?

**Comment by simonasdmd** [comment]
I'm a lady. Very, very lovely lady..

**Comment by evereux** [comment]
> Can't I use pycatia?

It would appear not ma'am. CATIA V5 is a per-requisite.

**Comment by simonasdmd** [comment]
Is it OK for me to install a CATIA V5?
Is this version of CATIA v5r2019 OK？

**Comment by simonasdmd** [comment]
Can the software you use open this data?
[JC.zip](https://github.com/evereux/pycatia/files/4455311/JC.zip)

**Comment by simonasdmd** [comment]
I found out I had this
![image](https://user-images.githubusercontent.com/42527845/78881822-ea67c980-7a89-11ea-8183-54f1bb706148.png)

**Comment by evereux** [comment]
I can't support anything other than issues with using pycatia. One of the requirements for that is having CATIA V5 installed. Will pycatia work with CATIA V5 r2019? I haven't and can't test that but it should. Will you be able to save a 3DXML to 3DS which you asked elsewhere? I don't think so but you have a later version of V5 available so maybe that can? I suspect your best bet is saving as CGR but we're veering off the topic for what this forum is for.

pycatia would typically be used to automate your CATIA V5 workflow. You must first find out if CATIA V5 itself can do what you expect before looking at pycatia. If you require support for CATIA V5 you can ask over at reddit: https://www.reddit.com/r/CATIA/.

I'm closing this topic as the installation issue itself has been resolved.

If you have further problems with pycatia (not CATIA V5 etc). Please open another thread but please first read the README file at: https://github.com/evereux/pycatia

**Comment by simonasdmd** [comment]
Oh, I see. Functions that CATIA V5 can achieve. Pycatia should be fine. If CATIA V5 does not have the ability itself, pycatia cannot.
Thank you very much. You've helped me a lot. I'll download V5 and try

**Comment by evereux** [comment]
You're welcome and good luck. 

I browse the reddit CATIA community sometimes myself so if I can help with CATIA V5 there I will.

**Comment by simonasdmd** [comment]
I think you can also try CATIA composer. Because it's not much different from CATIA V5.

**Comment by simonasdmd** [comment]
@evereux 

Hello. I have installed CATIA V5 R20 now. Can I use pycatia for this version?

![image](https://user-images.githubusercontent.com/42527845/79200029-6ab27400-7e68-11ea-92be-54574d1badc9.png)

It can be "saved as" WRL format. Can we use pycatia to do this?

![image](https://user-images.githubusercontent.com/42527845/79200206-a8170180-7e68-11ea-908e-d4baa4ef0458.png)

my test data:


[JC.zip](https://github.com/evereux/pycatia/files/4473947/JC.zip)

**Comment by evereux** [comment]
> I have installed CATIA V5 R20 now. Can I use pycatia for this version?

That should be fine.

> It can be "saved as" WRL format. Can we use pycatia to do this?

That should work. Why not just try it?
