### ISSUE TITLE
Assign a dimension by Pycatia ?

### ISSUE THREAD

**Issue by hosseintfr** [evereux/pycatia#190]
How can assign a dimension to a line in a drawing view by pycatia? is it possible to design a part in catia and then get dimensions of it by pycatia codes or not?!

**Comment by evereux** [comment]
> How can assign a dimension to a line in a drawing view by pycatia?

See https://github.com/evereux/pycatia/blob/master/pycatia/drafting_interfaces/drawing_dimensions.py (add() and add2())

> is it possible to design a part in catia and then get dimensions of it by pycatia codes or not?!

If you're talking of the drafting workbench again then I believe there is a CATIA V5 COM interface limitation in adding dimensions in generated views. It's OK if the view has manually drawn lines and arcs, that works OK I believe (never tried it). I found this out by googling.

```python
from pycatia import catia
from pycatia.drafting_interfaces.drawing_document import DrawingDocument

caa = catia()
application = caa.application
drawing_document = DrawingDocument(application.active_document.com_object)
sheets = drawing_document.sheets
sheet_1 = sheets.item(1)
views = sheet_1.views
view = views.item("Front view")
dimensions = view.dimensions
geom_elements = view.geometric_elements
for element in geom_elements:
    print(element)
```

Running this on a generated view only returned the AbsoluteAxis.
