### ISSUE TITLE
[BUG] __getitem__ and __iter__ accessing wrong .Item methods

### ISSUE THREAD

**Issue by mokrueger** [evereux/pycatia#195]
**Describe the bug**

A bunch of classes access the wrong .item method in the com_objects.
They should be accessing .Item

This leads to errors when using the respective class as iterators (also in for loops) or accessing lists via the bracket operator.

**To Reproduce**
Try getting an item via bracket operator / using them in a for loop.
e.g.
`for r in list(part.relations):
    ...`

**Expected behavior**
Get the right element.

**Screenshot**
Example of the wrong code in pycatia/pycatia/knowledge_interfaces/relations.py
<img width="507" alt="image" src="https://github.com/evereux/pycatia/assets/59337243/21dafa71-e85e-4697-afe2-05394b960933">

**Comment by mokrueger** [comment]
Addressed in https://github.com/evereux/pycatia/pull/196

**Comment by evereux** [comment]
Whilst technically it should be `Item` I'm failing to reproduce the issue in python 3.10 or 3.11.

This works fine:

```python

from pycatia import catia
from pycatia.mec_mod_interfaces.part_document import PartDocument

caa = catia()
part_document = PartDocument(caa.active_document.com_object)
part = part_document.part

for r in list(part.relations):
    print(r)
```

**Comment by mokrueger** [comment]
I see. I am using a variant of the Dispatch class which returns a win32com.client.DispatchBaseClass object. Here the attribtues are case sensitive. So that is causing the issues with me.

I'm using the modified com interface provided by Dassault, which is part of the 3DX package.

![image](https://github.com/evereux/pycatia/assets/59337243/7d2006ef-445a-4c19-bec0-8d0e7ac4b2d1)

So it shouldn't break anything, if we'd use the "accurate" case sensitivity here. Then I would not have to manually update the files for other pc's when using pycatia.

**Comment by evereux** [comment]
OK. Just wanted to understand why you were having issues as I was surprised this hadn't been raised before.

**Comment by evereux** [comment]
Closing as 0.6.7 now has these changes implemented.
