### ISSUE TITLE
class：HybridShapeFactory, how do i  draw a line?

### ISSUE THREAD

**Issue by Elemt** [evereux/pycatia#2]
How do I draw a line between two points

**Comment by evereux** [comment]
Hi Elemt,

I was planning on providing an example but I've just not had time.

Whilst it is possible with pycatia it's currently out of scope of the pycatias built in functions. To do it would require a good understanding of the underlying CATIA COM API and to use that. Though would not really require pycatia as I'm sure you could do that without it.

The question itself is rather open though ... do we assume we already have them selected within the script?

**Comment by evereux** [comment]
This is now possible with latest version.

Take a look at `example_015.py`. 

This creates a new part, creates two points and creates a line between them.

**Comment by evereux** [comment]
I'm closing this issue as I've provided an example and there has been no feedback.
