### ISSUE TITLE
[BUG] set_limitation not working for setting the circle limitations

### ISSUE THREAD

**Issue by CesarAero** [evereux/pycatia#203]
Dear support,

I believe that I found a bug in the code regarding the `set_limitation` funtion to set the circle limitation type when defining a circle with the hybrid shape factory. First I define the circle as it follows:

`circle_3p = hsf.add_new_circle3_points(p_x, p_z, p1) `
`circle_3p.name = "circle_3p"`
`circle_3p.set_limitation = 2`
`construction_elements.append_hybrid_shape(circle_3p)`

`# Update the document`
`document.part.update()`

But here you can see how I retrieve the limitation value using `get_limitation()` but it doesn't change after setting a different value with `.set_limitation`:

![image](https://github.com/evereux/pycatia/assets/161257492/871f30f1-f142-4429-a580-152d3838b101)

**Comment by mokrueger** [comment]
set_limitation is a function. Does it work with .set_limitation(1)?

**Comment by CesarAero** [comment]
You are right, it works now. Sorry for this, I thought that not having an error and not doing anything would mean that there is a bug...
