### ISSUE TITLE
[FEATURE REQUEST] Using pycatia to automate operations in machining modules like Prismatic Machining

### ISSUE THREAD

**Issue by mousjad** [evereux/pycatia#209]
Hi,

I would like to use python to prepare machining programs using pycatia. Currently, CATProcess are not even in the document type that are recognized. 

I would be open to help implementing it with a little guidance.

Thank you for your time and expertise.

**Comment by evereux** [comment]
I've updated the developement branch so that you can now do this:

```python
from pycatia import catia

caa = catia()
documents = caa.documents
documents.add('CATProcess')
```

**Comment by evereux** [comment]
You can now add this document type in 0.6.9.
