### ISSUE TITLE
Clarifications on how to explore the pycatia API

### ISSUE THREAD

**Issue by chrisoraruf** [evereux/pycatia#223]
Hi everyone, 

I am trying to approach CATIA as a data scientist and therefore as a non-engineer. After seeing the post about "Raising Issues/Asking Questions" I am a bit reluctant in asking, but I am simply trying to understand how I should approach the API to explore what I have to do. Example could be "read and print the specification tree of a certain CATPart". Having this task, how should I approach the research of something in the API?

Hope I will get some help

Cheers

**Comment by evereux** [comment]
You've closed the issue (figured it out?) but I'll just say that your best bet, as mentioned in the topic you referenced, is to work through the [examples](https://pycatia.readthedocs.io/en/latest/examples.html). Whilst doing so explore the objects returned and the class methods available to them within your IDE. If you're proficient in python this should get you up and running fairly quickly.

The API doesn't feel very intuitive, at least not at first. However, this isn't the result of a design decision by the pycatia project as pycatia is pretty much just a wrapper to interface with the CATIA V5 COM object.

There's currently no better introduction than this. I'd like to expand on the documentation at some point but other projects are getting in the way. :-(
