### ISSUE TITLE
[BUG] Missing  scale_on_extremities in DrawingArrow

### ISSUE THREAD

**Issue by siddhu2310** [evereux/pycatia#230]
**Describe the bug**
scale_on_extremities property  is missing in the **DrawingArrow** Object

**Expected behavior**
These below property need to be added in the **drawing_arrow.py**
![image](https://github.com/user-attachments/assets/ed6c9c8c-65ac-4905-b8e3-a617de740bd9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CATIA V5-6R2020
 - pycatia version : pycatia 0.7.3

**Comment by evereux** [comment]
According to the `V5Automation.chm` from `V5-6R2021` this was introduced in `V5-6R2018 GA`. However, I do have the `V5Automation.chm` from `V5-6R2018 GA` which was in fact used to generate pycatia. Must not have been properly documented at this stage by Dassault.

Anyways, this will get added but I'll need to go through all the new features and try and capture them too.  I'll also need to get pycatia to do a version check before the user runs the these new methods. Unless, I leave them to fail without telling the user why, maybe just comment on the fact in the doc string for the method? 

Unfortunately I don't currently have a way to test them anyway.

I'll need to think on this ....

**Comment by siddhu2310** [comment]
![image](https://github.com/user-attachments/assets/e8389f1d-30d4-4654-9eab-74b0c9553450)

### Property ScaleOnExtremities() As boolean
Returns or sets the scale on extremities mode.
**Example:**
This example retrieves the target element of head side on MyArrow drawing arrow.
```
 oScaleOnExtremities = MyArrow.ScaleOnExtremities
```

**Comment by evereux** [comment]
I've now added a bunch of new Classes, methods, properties and enums introduced between R2018 and R2021 which are listed in the [CHANGELOG.md](https://github.com/evereux/pycatia/blob/developement/CHANGELOG.md) for the developement branch. 

One of these additions is `DrawingArrow.scale_on_extremities`.

This will be included in next release which will be 0.8.0.

Thanks for letting me know about this.

I should be able to get the `V5Automation.chm` for `CATIA V5-6R2023` in a couple of weeks so I'll add anything missing between 
`CATIA V5-6R2021` > `CATIA V5-6R2023` then.

**Comment by siddhu2310** [comment]
@evereux

If Suppose user uses the lower version, notify them with error msg : These Methods or Class, Property not available with this CATIA version.

**Comment by evereux** [comment]
What I ended up doing was simply log a message to the console if the CATIA version is lower than the requirement.

0.8.0 is now released.
