### ISSUE TITLE
[QUESTION] User ref Properties

### ISSUE THREAD

**Issue by ptm-tm** [evereux/pycatia#232]
This is is not valid
```
product = document.product
user_properties = product.user_ref_properties
for i in range(1, user_properties.count + 1):
    print(user_properties.item(i).name,"=",user_properties.value)
```
but if we insert additional assignments - this code will be valid.
```
product = document.product
user_properties = product.user_ref_properties
for i in range(1, user_properties.count + 1):
    a=user_properties.item(i)
    print(a.name,"=",a.value)
```
its normally?

**Comment by ptm-tm** [comment]
sry my mistake... need add item(i) to value

**Comment by ptm-tm** [comment]
closed

**Comment by evereux** [comment]
You could do it like this:

```python

from pycatia import catia
from pycatia.product_structure_interfaces.product_document import ProductDocument

caa = catia()
product_document: ProductDocument = caa.active_document
product = product_document.product
user_ref_properties = product.user_ref_properties

for i in range(len(user_ref_properties)):
    index = i + 1
    print(f'{user_ref_properties.item(index).name}={user_ref_properties.item(index).value}')

```

Maybe a little easier to read? I should update the examples to reflect this when using range on a collection.

**Comment by ptm-tm** [comment]
ye) its more pythonic but im create simple for quick test..

**Comment by ptm-tm** [comment]
> You could do it like this:
> 
> ```python
> from pycatia import catia
> from pycatia.product_structure_interfaces.product_document import ProductDocument
> 
> caa = catia()
> product_document: ProductDocument = caa.active_document
> product = product_document.product
> user_ref_properties = product.user_ref_properties
> 
> for i in range(len(user_ref_properties)):
>     index = i + 1
>     print(f'{user_ref_properties.item(index).name}={user_ref_properties.item(index).value}')
> ```
> 
> Maybe a little easier to read? I should update the examples to reflect this when using range on a collection.

```
for i in user_ref_properties:
    print(i.name,i.value_as_string())
```
its more readable... but i cant use 
`i.value
`
