### ISSUE TITLE
How do I create a polyline? [was - self.part.update Error]

### ISSUE THREAD

**Issue by FaiqShahbaz** [evereux/pycatia#234]
I am encountering part update error on most of the designs i am doing via pyCatia, when run on different pc (with catia v5R17) its working alright (which means the code is okay). i have attached python code and the error i am encountering.

**Code:**
from pycatia import catia
from pycatia.mec_mod_interfaces.part_document import PartDocument

caa = catia()
application = caa.application
documents = application.documents
if documents.count > 0:
    for document in documents:
        document.close()
documents.add('Part')

document: PartDocument = application.active_document        
part = document.part                                        # Get Part
partbody = part.bodies[0]                                   # Get default PartBody by index
sketches = partbody.sketches                                # Get sketches on PartBody 
hybrid_bodies = part.hybrid_bodies                          # Get Hybrid Bodies 
hsf = part.hybrid_shape_factory                             # Get Hybrid Shape Factory 
shpfac = part.shape_factory                                 # Get Shape Factory 
selection = document.selection                              # Get document selection

plane_XY = part.origin_elements.plane_xy
plane_YZ = part.origin_elements.plane_yz
plane_ZX = part.origin_elements.plane_zx

part.in_work_object = partbody
L = 100
construction_elements = hybrid_bodies.add()
construction_elements.name = "construction_elements"

spline = hsf.add_new_spline()
spline.add_point(hsf.add_new_point_coord(L, 0, 0))
spline.add_point(hsf.add_new_point_coord(L/2, 0, L/8))
spline.add_point(hsf.add_new_point_coord(L/4, 0, L/2))
spline.add_point(hsf.add_new_point_coord(L/8, 0, L/2))
construction_elements.append_hybrid_shape(spline)
document.part.update()

Zdir = hsf.add_new_direction_by_coord(0, 0, 1)
surfRevolution = hsf.add_new_revol(spline, 0, 360, Zdir)
construction_elements.append_hybrid_shape(surfRevolution)
document.part.update()

polyline = hsf.add_new_polyline()
polyline.insert_element(hsf.add_new_point_coord(0,-1.5*L, 0), 0)
polyline.insert_element(hsf.add_new_point_coord(0, 1.5*L, 0), 1)
polyline.closure = False
construction_elements.append_hybrid_shape(polyline)
document.part.update()

Zdir = hsf.add_new_direction_by_coord(0, 0, 1)
surfExtrusion = hsf.add_new_extrude(polyline, 1.5*L, 0, Zdir)
surfExtrusion.symmetrical_extension = True
construction_elements.append_hybrid_shape(surfExtrusion)
document.part.update()

split1 = hsf.add_new_hybrid_split(surfRevolution, surfExtrusion, -1) 
split1.both_sides_mode = False
split1.intersection_computation = True
construction_elements.append_hybrid_shape(split1)
document.part.update()

selection.clear();
selection.add(polyline)
selection.add(spline)
selection.add(surfRevolution)
selection.add(surfExtrusion)
selection.vis_properties.set_show(1) # 0: Show / 1: Hide
selection.clear()

**Error:**
Traceback (most recent call last):
  File "D:\pythonProject\surfaces\split.py", line 113, in <module>
    document.part.update()
  File "D:\pyCatia Module\pythonProject\.venv\Lib\site-packages\pycatia\mec_mod_interfaces\part.py", line 906, in update
    return self.part.Update()
           ^^^^^^^^^^^^^^^^^^
  File "<COMObject <unknown>>", line 2, in Update
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'CATIAPart', 'The method Update failed', None, 0, -2147467259), None)

**Desktop:**
 - OS:  Windows 11
 - CATIA V5 (version V5-R20)
 - pycatia version (pycatia 08.0)

**Comment by evereux** [comment]
Can you please provide some code that runs, trips up on the error you have reported - see below and is properly [formatted](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) (see the section on formatting code). 

The traceback you supplied doesn't relate to the code you have provided. It trips up on line 113 but your code sample doesn't have that many lines?

**Comment by FaiqShahbaz** [comment]
[split.txt](https://github.com/user-attachments/files/17812950/split.txt)
this is the exact code which i used, there are other codes as well in which i am experiencing the exact same error,

Traceback (most recent call last):
File "D:\pythonProject\surfaces\split.py", line 113, in
document.part.update()
File "D:\pyCatia Module\pythonProject.venv\Lib\site-packages\pycatia\mec_mod_interfaces\part.py", line 906, in update
return self.part.Update()
^^^^^^^^^^^^^^^^^^
File "<COMObject >", line 2, in Update
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'CATIAPart', 'The method Update failed', None, 0, -2147467259), None)

**Comment by evereux** [comment]
``` python
polyline.insert_element(hsf.add_new_point_coord(0,-1.5*L, 0), 0)
```

The `polyline.insert_element` position should start at 1, not 0. 😃

In the future, if your script is breaking on a specific problem, in this case updating part after inserting the polyline, you should strip down your script to tackle that and that only. 

A polyline example

```python

from pycatia import catia
from pycatia.mec_mod_interfaces.part_document import PartDocument


caa = catia()
application = caa.application
document: PartDocument = application.active_document
part = document.part
hsf = part.hybrid_shape_factory
hybrid_bodies = part.hybrid_bodies
construction_geometry = hybrid_bodies.item('ConstructionGeometry')

point_1 = hsf.add_new_point_coord(0, 0, 0)
point_2 = hsf.add_new_point_coord(100, 100, 100)
construction_geometry.append_hybrid_shape(point_1)
construction_geometry.append_hybrid_shape(point_2)
part.update()

ref_point_1 = part.create_reference_from_object(point_1)
ref_point_2 = part.create_reference_from_object(point_2)

polyline = hsf.add_new_polyline()
polyline.insert_element(ref_point_1, 1)
polyline.insert_element(ref_point_2, 2)
polyline.closure = False

construction_geometry.append_hybrid_shape(polyline)

part.update()
```

**Comment by maipj** [comment]
I also have some questions on my end regarding the update of the part. Below are some of my size updates, which may include parameter values such as size, offset, and boss. I have used the following methods to modify them all, but there have been errors. I would like to know how to modify all the parameters of CATIA or how to determine if they can be modified. If anyone knows, please let me know. I would be very grateful!

code down
        try:
            self.open_CATPart_file(cad_path)
            part_document: PartDocument = self.Catia_Instance.active_document
            part = part_document.part
            parameters = part.parameters
            for item in size_data:
                val = str_to_float(item[1])
                data = parameters.get_item_by_name(item[0])
                length = Length(data.com_object)
                length.value = val
                part.update()
        except Exception as ex:
            print("update failed", ex)

**Comment by evereux** [comment]
Please take a look at the [examples](https://pycatia.readthedocs.io/en/latest/examples.html) regarding parameters, specifically: https://github.com/evereux/pycatia/blob/master/examples/example__parameters__002.py

If you still have a problem please open a new issue providing a complete code example demonstrating the problem you are having along with any error message you have received.
