### ISSUE TITLE
How to export STEP file from Surf using pycatia package?

### ISSUE THREAD

**Issue by selvakarna** [evereux/pycatia#3]
How to export STEP file from Surf using pycatia package?

**Comment by evereux** [comment]
This isn't currently directly available using pycatia but it can be done by accessing the Document com object. See the file V5Automation.chm within your CATIA installation for more information.

`from pycatia import CATIAApplication

# path to file to open.
file_name = r'Part1.CATPart'

catia = CATIAApplication()
# open document
documents = catia.documents()
documents.open(file_name)

document = catia.document()
# export data to new format.
document.document.ExportData(r"C:\Users\paul\pycatia\exported_stp", "stp")
# close document
document.close()`

**Comment by evereux** [comment]
I'm an idiot. I did add this feature.

    document.document.ExportData(r"C:\Users\evereux\pycatia\exported_stp", "stp")

can be

    document.export_data(r"C:\Users\evereux\pycatia\exported_stp", "stp")


You can use the documents.open() method to open other file types.

**Comment by selvakarna** [comment]
Hi @evereux , 

when i install pycatia in my Linux machine ,i got error below, how to solve this


ERROR: No matching distribution found for pywin32==224 (from pycatia)

**Comment by selvakarna** [comment]
i am asking surface to step file? @evereux

**Comment by evereux** [comment]
Do you have CATIA V5 running in Linux? I know it's possible but it's technically a Windows application as is pywin32.

**Comment by evereux** [comment]
I'm closing this ticket as I've no feedback from OP.
