### ISSUE TITLE
How to execute python script without python installed?

### ISSUE THREAD

**Issue by tcrakshi** [evereux/pycatia#32]
How to call  the python code in catia?
if catia user dont have python editor in his machine, how it will work?
is there any mechanism to tackles this issue?

because native catia user dont have background of coding , so how we can deploy too the user to launch the python code in Catia interface. (Like catia native commands)

Regards,
Rakshith

**Comment by evereux** [comment]
You can use py2exe (or similar) to compile an executable for the end user to run if they don't have python. Be warned though some companies virus checkers don't like the compiled result.

Otherwise, you have to have python installed.

**Comment by evereux** [comment]
ps I can't support how you would do that right now.

**Comment by tcrakshi** [comment]
ya, i am also thinking to do in pyinstaller or py2exe .

**Comment by evereux** [comment]
Hmmm, this has got me thinking. It might be a good idea to provide a windows binary as a part of this project ...

**Comment by evereux** [comment]
pycatia now has a win32 binary in the repository. See https://pycatia.readthedocs.io/en/latest/windows_builds.html.

**Comment by evereux** [comment]
I'm closing this ticket. The request has been satisfied.

If there are issues with the executable please open a new ticket.
