### ISSUE TITLE
Generate CATPart From Product

### ISSUE THREAD

**Issue by tcrakshi** [evereux/pycatia#33]
is it possible to do Generate CATPart From Product in python code?
if it is possible, can anyone share some snippet of that code?

**Comment by evereux** [comment]
It is not currently possible with pycatia but you could hack it. It seems that whilst the CATIA COM interface can do it it's not documented thus wasn't imported.

reference:  http://www.coe.org/p/fo/et/thread=28139

I may add this at a later date.

**Comment by tcrakshi** [comment]
thanks for reply, please keep me inform, once you added this feature in catia. it is very useful.

**Comment by evereux** [comment]
Agreed. I've had to create ALLCATParts many many times over the years.

I'll leave this ticket open and report progress in the future. Time permitting I may tackle this this week

**Comment by evereux** [comment]
This has been added to pycatia 0.3.9. See https://pycatia.readthedocs.io/en/latest/api/pycatia/product_structure_interfaces/product.html#pycatia.product_structure_interfaces.product.Product.generate_ALLCATPart

usage would be ``product.generate_ALLCATPart(product)`` which would return a document object.

**Comment by tcrakshi** [comment]
hey, its very good to see that command in pycatia.
i will use and give feedback soon

**Comment by tcrakshi** [comment]
May i know, when pycatia 0.3.9 will be release?

**Comment by evereux** [comment]
I forgot to upload to pypi! Sorry about that. I've done that now.

**Comment by tcrakshi** [comment]
hi

i am trying to generate_ALLCATPart , but no luck.
i am using pycatia 0.4.0 version,  please do a needful help.

Requirement: Generate the catprt for root product or main product

**my Code:**
```Python code
from pycatia import catia

documents = catia.active_document
rootProduct = documents.product()
generateCatPart = rootProduct.generate_ALLCATPart(rootProduct)

```
**Error:**
```
Traceback (most recent call last):

  File "<ipython-input-4-9beb400b0747>", line 1, in <module>
    runfile('C:/Users/A337885/Desktop/PY/untitled2.py', wdir='C:/Users/A337885/Desktop/PY')

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/A337885/Desktop/PY/untitled2.py", line 5, in <module>
    generateCatPart = rootProduct.generate_ALLCATPart(rootProduct)

AttributeError: 'Product' object has no attribute 'generate_ALLCATPart'

```

**Comment by low-life-products** [comment]
See the changelog for version 0.4.

**Comment by tcrakshi** [comment]
i gone through  changelog for version 0.4 and .39 still not working.
can you guide me where i am doing mistake or if provide some snippet, it would be very useful.

**My code:**
``` python code
from pycatia import catia
caa = catia()
document = caa.active_document
rootProduct = document.product()
part = rootProduct.generate_ALLCATPart(rootProduct)

``` 
**error:**
``` 
runfile('C:/Users/A337885/Desktop/PY/untitled3.py', wdir='C:/Users/A337885/Desktop/PY')
Traceback (most recent call last):

  File "<ipython-input-17-cbe849f76d4a>", line 1, in <module>
    runfile('C:/Users/A337885/Desktop/PY/untitled3.py', wdir='C:/Users/A337885/Desktop/PY')

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/A337885/Desktop/PY/untitled3.py", line 24, in <module>
    part = rootProduct.generate_ALLCATPart(rootProduct)

  File "C:\Users\A337885\AppData\Roaming\Python\Python37\site-packages\pycatia\product_structure_interfaces\product.py", line 946, in generate_ALLCATPart
    part = product.com_object.GetItem("DECProductToPart")

  File "<COMObject <unknown>>", line 2, in GetItem

com_error: (-2147352567, 'Exception occurred.', (0, 'CATIAProduct', 'The method GetItem failed', None, 0, -2147467263), None)

```

**Comment by evereux** [comment]
Can you manually try activating terminal node and activating design mode on the root product first and then run the script again please? I can't test myself just now.

If this is the issue I'll make pycatia throw a nicer error / hint to the user in the next version.

**Comment by tcrakshi** [comment]
before running .py script, i have done design mode and activate terminal node as well. still not working

**Comment by evereux** [comment]
OK.I'll test this out in the morning.

**Comment by evereux** [comment]
I created a new product with one part in it that contained a solid block.

Your script ran fine.

If I run the script on a Part I get your error.

```python

from pycatia import catia

caa = catia()
document = caa.active_document
if document.is_product:
    product = document.product()
    # generate_ALLCATPart() returns a Document object 
    # so best name it document so it makes more sense in the future.
    document = product.generate_ALLCATPart(product)
else:
    print(f"Document '{document.name}' is not a product!")
```

**Comment by tcrakshi** [comment]
I  ranned same script above what you have provided, still getting same error.
i tried in exciting and new  product still no luck 

i am using R27 catia,  windows10 , python 3.7.

if it is possible, can we have a call through skype or webex?

regrds,
rakshith

**Comment by tcrakshi** [comment]
i am getting error in this line: 
**part = product.com_object.GetItem("DECProductToPart")**  in product.py file

``` python 
@staticmethod
    def generate_ALLCATPart(product: 'Product') -> 'Document':
        """

        Generate an ALLCATPart (CATPart) from CATProduct.

        :param Product product:
        :return: Document
        :rtype: Document
        """

        from pycatia.in_interfaces.document import Document

        part = product.com_object.GetItem("DECProductToPart")
        part.Run()
        part = part.GetResult()

        return Document(part)
```

**Comment by low-life-products** [comment]
Is think this is possibly a CATIA V5 license issue.

**Comment by tcrakshi** [comment]
what licence required?

**Comment by evereux** [comment]
This is the one I believe: https://www.3ds.com/products-services/catia/products/v5/portfolio/domain/Infrastructure/product/DF1/?woc=%7B%22category%22%3A%5B%22category%2Fchampions%22%5D%7D&wockw=card_content_cta_1_url%3A%22https%3A%2F%2Fblogs.3ds.com%2Fcatia%2F%22

**Comment by tcrakshi** [comment]
Hi,
yes you are correct,  its required DF1 lic.  
i checked with DF1 lic, now its working.

just thought:
if pycatia  generate all catpart works without DF1 licence, it will be more useful.


regards,
Rakshith

**Comment by evereux** [comment]
Hmmm. I guess this would technically be possible ... loop through each
product > part, copy all visible elements, paste into target part.

Why not write a script yourself and share it? :-) I'll add it to the
examples and if it proves robust I'll add it to pycatia.

The current method will always use the license DF1. I'll add a check
for the license in the next version so that the user gets a warning.

**Comment by tcrakshi** [comment]
yes, that would be great:


i already have a code in VB script, but there cons are more
1. if data size is more it will take time
2. position : if we go for copying on individual visual part level, there will be problem in instance ( need to take care and need to build logic)


now i am slowly getting into python, yes in future i will give try in python.

**Comment by tcrakshi** [comment]
hi, 
i have question regarding generate cat product
1. is it will work for only root product or is it capable of work on selected product?

**Comment by tcrakshi** [comment]
ya, i got it, it will work for selected product also

**Comment by evereux** [comment]
I'm closing this now as I believe the original question has been answered.

**Comment by VBG8** [comment]
Tcrakshi, how did you manage to transform a product within a rootproduct into a catpart?
