### ISSUE TITLE
How to add attributes like hide, show , color properties to specific object?

### ISSUE THREAD

**Issue by tcrakshi** [evereux/pycatia#37]

**Comment by tcrakshi** [comment]
catia.active_document.selection.vis_properties.set_show(1) ,
 i know above method through selection of object, we can add attribute.
but i want know, is there any method or property in object itself?

**Comment by evereux** [comment]
Take a look at the API https://pycatia.readthedocs.io/en/latest/api_index.html or use a Python IDE that lets your explore the source.

**Comment by evereux** [comment]
Also, there are examples that cover some of this.

Please show some code to show what you've tried, what you expected and what didn't work. I'm closing this until then.
