### ISSUE TITLE
Is it possible to get list of files from Missing Files dialog on open?

### ISSUE THREAD

**Issue by imchaotic** [evereux/pycatia#48]
Currently if I open a CATProduct that is missing some components, I get a popup asking me to find those files.

Is it possible to get that list of files from the dialog window?

**Comment by evereux** [comment]
I don't know if that functionality is built into the CAA API. But, each Product has a [path()](https://github.com/evereux/pycatia/blob/afa0fa374728080b33410cacaac6077c39b2464c/pycatia/product_structure_interfaces/product.py#L1345) method that returns a [Path](https://docs.python.org/3/library/pathlib.html) object. You could use that to see if the document [exists](https://docs.python.org/3/library/pathlib.html#pathlib.Path.exists).

**Comment by evereux** [comment]
Closing this as there has been no response.
