### ISSUE TITLE
AnalysisImage processing

### ISSUE THREAD

**Issue by dastaninho** [evereux/pycatia#55]
After computing a Principal stress value with average Iso, I exported the data as a csv file but I only got the upper layer results. 
How can I access the layer filter "Upper and Lower" in order to have both values in my csv file ? 

Thank you very much

**Comment by evereux** [comment]
I'm don't understand how this relates to pycatia. Can you please provide some more information?

**Comment by dastaninho** [comment]
I fixed it !

**Comment by evereux** [comment]
Please take the time to explain what your problem actually was and what you did to resolve it. It may help others.
