### ISSUE TITLE
Mass properties for complete part and individual bodies

### ISSUE THREAD

**Issue by tcrakshi** [evereux/pycatia#56]
Hi,
vi
is it pycatia able to fetch mass for part  and individual body?
if it is there please give me one example code(Snippet).

thanks

**Comment by Tian-Jionglu** [comment]
Hi,
this code would work.
https://github.com/evereux/pycatia/issues/10#issuecomment-699983919

**Comment by Tian-Jionglu** [comment]
I found a quick method to get mass property.
try `product.analyze.mass`

**Comment by evereux** [comment]
I'm closing this as there is no feedback and from @Tian-Jionglu's helpful link and reply.
