### ISSUE TITLE
No attribute Open in catia.documents ? how to read CATPart?

### ISSUE THREAD

**Issue by selvakarna** [evereux/pycatia#6]
doc.open('1.CATPart')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'open':

**Comment by evereux** [comment]
Can you please respond to my question to you here: https://github.com/evereux/pycatia/issues/3.

Also, there are several examples in the documentatio that include the opening of a .CATPart which you aren't following. I have also provided an example in the issue linked above which is nothing like what you are trying to do here.

You can't open a CATPart without even at least importing the module you are raising a ticket on.

**Comment by selvakarna** [comment]
Hi @evereux , you dont know how to solve this issue ????????????? okay thanks
