### ISSUE TITLE
Improve the behavior of broken links [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Tian-Jionglu** [evereux/pycatia#71]
Suppose that we opened a root product, which has 5 sub products. And one of the sub product's link is broken.
Then we try the script below:
```
from pycatia import catia

caa = catia()
document = caa.active_document
product = document.product()
products = product.products
for sub_prd in products:
    print(sub_prd.file_name)
```
An **com_error** will occur when the process meet the broken link.
I think it's better to raise a "BrokenLinkErr" here. It would be more friendly for programmer to debug. (It take me a lot of time to find out this error when looping in a huge tree)

Or, if there is better solution to solve broken link problems, it is appreciated.

**Comment by evereux** [comment]
Thanks for the report!

I have submitted this patch: [Improve handling of Product.reference_product for broken links.](https://github.com/evereux/pycatia/commit/7efc7ecc2d113c37cfc94cee3bf2e5c0a85fb5cc).

**Comment by evereux** [comment]
I'll be changing this patch as it has broken things ..

**Comment by evereux** [comment]
OK. I think it's better now.

I didn't specifically raise a "BrokenLinkErr" as I don't know if other issues could also raise a com_error for this case.

**Comment by Tian-Jionglu** [comment]
There are more methods need this improvement, like:
- [ ] Product.part_number
- [ ] Product.source
Should we do the same change one by one?
I'm sure Product.part_number is often used.

**Comment by evereux** [comment]
Sure!

**Comment by Tian-Jionglu** [comment]
Commit https://github.com/evereux/pycatia/pull/77/commits/6b45a5360f3a3eea3ab1d0ed332ae157bfebc5de to improve `Product.part_number` and `Product.soure` following this topic.
