### ISSUE TITLE
Catia V5 composites

### ISSUE THREAD

**Issue by Kanfit** [evereux/pycatia#75]
**Is your feature request related to the CAA V5 Automation API?**
CompositesServices method GetCompositesType

Seems like composites services are not available. Have you tried to get composites type?
This feature may be useful to get info from stacking that is later can be used for different operations.

**Comment by evereux** [comment]
It's unlikely that this will ever be added by myself as I don't have currently access to the appropriate licenses required for development and testing. Or indeed the time.

**Comment by Kanfit** [comment]
Seems like composites won't be ever exposed.
