### ISSUE TITLE
Order points collection for output

### ISSUE THREAD

**Issue by Kanfit** [evereux/pycatia#78]
I try to output points coordinates in an order one by one. In the Catia tree points aren't ordered. Points are created in two steps. First step is end points creation. Second step is points on curve by ratio creation. Points are not ordered in the Catia tree. Now, for export points must be in an order. How can it be done?

**Comment by evereux** [comment]
I'm not sure how you actually want the points ordered?

Any chance of labelled screenshots?

**Comment by Kanfit** [comment]
Please see attached.
![Capture](https://user-images.githubusercontent.com/51846234/104121851-2649fb00-534a-11eb-8d39-ec8cecc64dfe.JPG)

**Comment by evereux** [comment]
Where are points 9 and 10? Why do you then jump to point 4?

Either way I can't think of any simple logic using the CATIA API to apply to this situation. Why is the order important? Can the points be ordered by coordinates somehow? This is something you could do with python itself.

**Comment by Kanfit** [comment]
Sorry. Output should be: 3, 5, 6, 7, 8, 9, 10 and 4. I need that for laser projection. To understand requirement better, imagine you create a spline using these points. 
![Capture](https://user-images.githubusercontent.com/51846234/104124929-4f738700-535c-11eb-9631-b821bca1b5ae.JPG)

**Comment by evereux** [comment]
Got it.

If it's possible I would change the way you create the points. Create the points on the line in one step using `Points And Plane Repetition` and check `With End Points`. I'm sure they'll be in the right order then.

**Comment by Kanfit** [comment]
You are right. Will try that. Work on reverse engineering of VB6 app (For laser projection).

**Comment by RebelYoung** [comment]
@evereux Hello, is there `add_new_points_repetition` function in `0.8.2` ?

**Comment by evereux** [comment]
@RebelYoung No. You would need to create a function that does that yourself. Dassault haven't exposed that from what I can see.
