### ISSUE TITLE
[FEATURE REQUEST] MBD (Part/Product)

### ISSUE THREAD

**Issue by Kanfit** [evereux/pycatia#79]
Any methods to extract captures to PowerPoint from a catpart or a product? Mostly product.
Some of our customers use phantom part in assembly that includes all the assembly requirements. Takes time to take screen grabs. 
So, get_captures method will be a nice thing.

**Comment by Tian-Jionglu** [comment]
Issue #57 may help.

**Comment by Kanfit** [comment]
Thanks. Will try that

**Comment by evereux** [comment]
Can this be closed?
