### ISSUE TITLE
Add funct_system_interfaces

### ISSUE THREAD

**Issue by Tian-Jionglu** [evereux/pycatia#88]
In branch [funct_system_interfaces](https://github.com/Tian-Jionglu/pycatia/tree/funct_system_interfaces) added it a new package **funct_system_interfaces**.
It can normally work for my current use.
This package follows the strategy discussed in issue #87 . When #87 is clear, I will make a pull request for this package.

**Comment by evereux** [comment]
Should be good to go now.

Please add some basic tests for the package. These are important.

**Comment by Tian-Jionglu** [comment]
I put this task in TODO.
Please give me some time.

**Comment by evereux** [comment]
No rush my friend. No rush.

**Comment by evereux** [comment]
I'm closing this as the preliminary work has been done. If any specifc issues arise please open a new ticket.
