### ISSUE TITLE
[BUG]pywintypes.com_error when executing example_003

### ISSUE THREAD

**Issue by CarrotC** [evereux/pycatia#93]
**Describe the bug**
[2021-07-12 19:14:46,962] INFO in documents: Opening document "D:\data\CADModels\catia\BHHelicopter\M24.CATPart".
[2021-07-12 19:14:47,413] WARNING in document: This method may be deprecated in future versions.
Traceback (most recent call last):
  File "D:/workspace/python/STLCompare/PointsFromCATPart.py", line 30, in <module>
    selected = document.search_for_items(['Point'])
  File "D:\workspace\python\STLCompare\venv\lib\site-packages\pycatia\in_interfaces\document.py", line 844, in search_for_items
    selection.Search(query_string)
  File "<COMObject <unknown>>", line 2, in Search
pywintypes.com_error: (-2147352567, '发生意外。', (0, 'CATIASelection', '方法 Search 失败', None, 0, -2147467259), None)

**To Reproduce**
run the example_003 code with a CATPart file

**Expected behavior**
get a csv file of the points of the CATPart

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CATIA V5 version:  V5-6R2017
 - pycatia version: pycatia 0.5.0

**Additional context**
Besides, I want to ask whether this example code is to get points by sampling the CAD model to a point cloud or get the vertex.

**Comment by Tian-Jionglu** [comment]
Hi, this is caused by you Chinese environment.
This example use search method, and only valid for name `Point`.

**Comment by CarrotC** [comment]
> Hi, this is caused by you Chinese environment.
> This example use search method, and only valid for name `Point`.
Hi, there is no Chinese word in my path, or you mean I should change the language of my computer to English?  
I'm not familiar with CATIA. is it none if I search name `Point` in a Cylinder CATPart?

**Comment by evereux** [comment]
If Points were used to define the Cylinder and they are named Point in your tree the script example should find them.

If you want to find the centre points at the ends of a Cylinder solid, and those Points aren't used for construction, you'll need to tackle this differently.

**Comment by CarrotC** [comment]
@evereux  Get it, thanks. 
Do you know how to deal with the pywintypes.com_error reported?

**Comment by evereux** [comment]
Can you provide a picture of your part tree.

**Comment by evereux** [comment]
For example
![2021-07-13_14-41](https://user-images.githubusercontent.com/19860292/125462363-5fb076a4-af54-458f-b1cb-e2ccd51e8669.png)

**Comment by CarrotC** [comment]
I tested several CATPart including a Cylinder without Points, and the CATPart produced by example_005. Their part trees are 
![image](https://user-images.githubusercontent.com/31116613/125549727-26939685-95e2-4ca4-b511-46ce6af2bd98.png)
![image](https://user-images.githubusercontent.com/31116613/125549778-17cf530b-fe02-4fea-b6d0-067a993c0832.png)
If this error caused by the CATPart, could you upload an example CATPart that runs well?

**Comment by CarrotC** [comment]
This problem is solved after I changed the Interface Language to English.
And I understand the concept of Point in CATIA with your explanation.
Thanks a lot.
