### ISSUE TITLE
[SUPPORT REQUEST] how to create shapes in a added body

### ISSUE THREAD

**Issue by CarrotC** [evereux/pycatia#95]
I want to create shapes in body2 I added by 
```
    bodies = part.bodies
    body2 = bodies.add()
```
I browsed the examples and found code in example_016:
```
part = document.part
hbs = part.hybrid_bodies
geom_set = hbs.add()
geom_set.append_hybrid_shape(point_1_3D)
```
I tried 
```
bodies = part.bodies
body2 = bodies.add()
hbs = body2.hybrid_bodies
hb = hbs.add()
hb.append_hybrid_shape(cylinder)
```
but got _AttributeError: 'NoneType' object has no attribute 'Add'_ in `hb = hbs.add()`
I can't find difference between these two hybrid_bodies by the API, and don't know other ways to create shapes in a body I added. 
Could you show some examples about how to create shapes in a body?

**Comment by evereux** [comment]
If you look at the end of example_016 ..


```python
# excerpt from example_016.py

# create the pad from sketch
main_body = part.main_body
part.in_work_object = main_body
part_shape_factory = part.shape_factory
part_shape_factory.add_new_pad(sketch, 5)


part.update()
```

You need to make the body you want to create the shape in the in_work_object

```python

bodies = part.bodies
new_body = bodies.add()
new_body.name = 'New Body'
part.in_work_object = new_body
part_shape_factory = part.shape_factory
part_shape_factory.add_new_pad(sketch, 5)

part.update()

```
