### ISSUE TITLE
Incorrect VBA Function Output[BUG]

### ISSUE THREAD

**Issue by Mebiza** [evereux/pycatia#99]
**Describe the bug**
Some functions would return an error on the output due to a missing comma separating output parameters

**To Reproduce**
Call get_point_at_param on a Curve2D object.
start_point = curve.get_point_at_param(sp) -> Error

**Expected behavior**
Te function should return the Point object for the given parameter value on the curve

**Screenshots**
pycatia code for get_point_at_param:
![image](https://user-images.githubusercontent.com/90345490/132558000-6b644d9e-197d-4c5e-92e5-7fe0c1a155b4.png)
How it should be:
![image](https://user-images.githubusercontent.com/90345490/132558142-76282290-00f4-41f9-bf64-f53140581997.png)

Adding the comma before oPoint solves the issue

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CATIA V5 version V5-6R2018
 - pycatia version [e.g. pycatia 0.4.4] i believe it still exists on 0.5.1

**Additional context**

**Comment by evereux** [comment]
Thanks for this. I'll get this done in the next few days.

**Comment by evereux** [comment]
Released new version 0.5.2 that fixes this.
